name: autophagy_gui_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - scikit-image
  - pandas
  - scipy
  - tifffile
  - napari
  - pyqt=5.15
  - qtpy
  - magicgui
  - superqt
  - cellpose
  - networkx  # leave version flexible
  - pip
  - pip:
      - pydantic
