name: autophagy_gui_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - napari=0.5.5
  - pyqt=5.15.11
  - qt-main=5.15.15
  - qtpy=2.4.3
  - magicgui=0.10.0
  - superqt=0.7.3
  - tifffile
  - imageio
  - matplotlib=3.10.1
  - numpy=1.26
  - scipy=1.15
  - pandas
  - seaborn
  - scikit-image=0.21
  - scikit-learn
  - networkx
  - openpyxl
  - tqdm
  - pyyaml
  - plotly
  - ipython
  - pip
  - pip:
      - cellpose==3.1.1.1
      - opencv-python-headless==4.11.0.86
      - pydantic==2.11.4
