name: image_analysis_env
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - absl-py=2.2.0
  - adwaita-icon-theme=48.0
  - affogato=0.4.2
  - aicsimageio=4.14.0
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - alabaster=1.0.0
  - annotated-types=0.7.0
  - anyio=4.7.0
  - aom=3.9.1
  - appdirs=1.4.4
  - appnope=0.1.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - async-timeout=5.0.1
  - atk-1.0=2.38.0
  - attrs=25.3.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.1
  - aws-c-common=0.12.3
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.4
  - aws-c-http=0.10.1
  - aws-c-io=0.19.1
  - aws-c-mqtt=0.13.0
  - aws-c-s3=0.8.0
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.32.6
  - aws-sdk-cpp=1.11.510
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - babel=2.17.0
  - beautifulsoup4=4.12.3
  - bfio=2.3.0
  - bioimageio.core=0.8.0
  - bioimageio.spec=0.5.4.1
  - blas=1.0
  - bleach=6.2.0
  - blosc=1.21.6
  - bokeh=3.6.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-blosc2=2.17.1
  - ca-certificates=2025.6.15
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachey=0.2.1
  - cairo=1.18.4
  - cffi=1.17.1
  - charls=2.4.2
  - click-default-group=1.2.2
  - cloudpickle=3.1.1
  - coin-or-cbc=2.10.12
  - coin-or-cgl=0.60.9
  - coin-or-clp=1.17.10
  - coin-or-osi=0.108.11
  - coin-or-utils=2.11.12
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.2
  - cpython=3.10.17
  - cycler=0.12.1
  - cytoolz=1.0.1
  - dask-core=2025.5.0
  - dav1d=1.2.1
  - debugpy=1.8.14
  - decorator=5.2.1
  - defusedxml=0.7.1
  - distributed=2025.5.0
  - distro=1.9.0
  - dnspython=2.7.0
  - docformatter=1.7.7
  - docstring_parser=0.16
  - docutils=0.21.2
  - elementpath=5.0.2
  - email-validator=2.2.0
  - email_validator=2.2.0
  - epoxy=1.5.10
  - et_xmlfile=1.1.0
  - executing=2.2.0
  - expat=2.7.0
  - fasteners=0.19
  - ffmpeg=4.3.2
  - fftw=3.3.10
  - filelock=3.18.0
  - flexcache=0.3
  - flexparser=0.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.13.3
  - freetype-py=2.5.1
  - fribidi=1.0.10
  - frozenlist=1.5.0
  - fsspec=2023.4.0
  - gdk-pixbuf=2.42.12
  - gettext=0.21.0
  - gflags=2.2.2
  - giflib=5.2.2
  - glib=2.84.0
  - glib-tools=2.84.0
  - glog=0.7.1
  - glpk=5.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.15
  - graphite2=1.3.13
  - graphviz=12.0.0
  - grpcio=1.71.0
  - gst-plugins-base=1.24.11
  - gstreamer=1.24.11
  - gtk2=2.24.33
  - gtk3=3.24.43
  - gts=0.7.6
  - h11=0.14.0
  - h2=4.2.0
  - h5py=3.13.0
  - harfbuzz=9.0.0
  - hdf5=1.14.3
  - heapdict=1.0.1
  - hicolor-icon-theme=0.17
  - hpack=4.1.0
  - hsluv=5.0.4
  - httpcore=1.0.2
  - httpx=0.28.1
  - huggingface_hub=0.17.3
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - imageio=2.26.0
  - imageio-ffmpeg=0.6.0
  - imagesize=1.4.1
  - imath=3.1.12
  - importlib_resources=6.5.2
  - in-n-out=0.2.1
  - ipykernel=6.29.5
  - ipython=8.36.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.4.2
  - json5=0.9.25
  - jsonschema=4.23.0
  - jsonschema-specifications=2025.4.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jxrlib=1.1
  - kornia=0.8.1
  - kornia-rs=0.1.8
  - krb5=1.21.3
  - lame=3.100
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.17
  - lemon=1.3.1
  - lerc=4.0.0
  - libabseil=20250127.1
  - libaec=1.1.3
  - libarrow=20.0.0
  - libarrow-acero=20.0.0
  - libarrow-dataset=20.0.0
  - libarrow-substrait=20.0.0
  - libasprintf=0.24.1
  - libavif16=1.3.0
  - libblas=3.9.0
  - libboost=1.86.0
  - libboost-python=1.86.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp15=15.0.7
  - libclang-cpp17=17.0.6
  - libclang13=19.1.2
  - libcrc32c=1.1.2
  - libcurl=8.13.0
  - libcxx=20.1.5
  - libde265=1.0.15
  - libdeflate=1.24
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.0
  - libffi=3.4.4
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgd=2.3.3
  - libgettextpo=0.24.1
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.84.0
  - libgoogle-cloud=2.36.0
  - libgoogle-cloud-storage=2.36.0
  - libgrpc=1.71.0
  - libheif=1.19.7
  - libhwy=1.2.0
  - libiconv=1.18
  - libidn2=2.3.4
  - libintl=0.24.1
  - libintl-devel=0.24.1
  - libjpeg-turbo=3.1.0
  - libjxl=0.11.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.7
  - libllvm17=17.0.6
  - libllvm19=19.1.2
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.64.0
  - libogg=1.3.5
  - libopenblas=0.3.29
  - libopentelemetry-cpp=1.20.0
  - libopentelemetry-cpp-headers=1.20.0
  - libopus=1.5.2
  - libparquet=20.0.0
  - libpng=1.6.47
  - libpq=16.9
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - librsvg=2.58.4
  - libsodium=1.0.20
  - libsqlite=3.49.2
  - libssh2=1.11.1
  - libtasn1=4.19.0
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libtorch=2.6.0
  - libunistring=0.9.10
  - libutf8proc=2.10.0
  - libuv=1.50.0
  - libvigra=1.12.2
  - libvorbis=1.3.7
  - libwebp=1.5.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libxslt=1.1.39
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - llvm-openmp=20.1.5
  - locket=1.0.0
  - loguru=0.7.3
  - lxml=4.9.4
  - lz4=4.4.4
  - lz4-c=1.10.0
  - magicgui=0.10.0
  - markdown=3.8
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib-base=3.10.3
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - micro_sam=1.4.0
  - mistune=3.1.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - mrc=0.3.1
  - mrcfile=1.5.4
  - msgpack-python=1.1.0
  - multidict=6.1.0
  - munkres=1.1.4
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - napari=0.5.5
  - napari-base=0.5.5
  - napari-console=0.1.3
  - napari-plugin-engine=0.2.0
  - napari-plugin-manager=0.1.6
  - napari-svg=0.2.1
  - natsort=8.4.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nd2=0.10.3
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.4.2
  - nifty=1.2.4
  - nlohmann_json=3.11.2
  - nomkl=1.0
  - notebook=7.3.2
  - notebook-shim=0.2.4
  - npe2=0.7.8
  - nspr=4.36
  - nss=3.111
  - numba=0.61.2
  - numcodecs=0.13.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - numpydoc=1.8.0
  - ome-types=0.6.0
  - ome-zarr=0.11.1
  - openexr=3.3.3
  - openh264=2.1.1
  - openjpeg=2.5.3
  - openpyxl=3.1.5
  - openssl=3.5.0
  - optree=0.15.0
  - orc=2.1.2
  - overrides=7.4.0
  - packaging=25.0
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - pango=1.54.0
  - parso=0.8.4
  - partd=1.4.2
  - patsy=1.0.1
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.2.1
  - pint=0.24.4
  - pip=25.0
  - pixman=0.46.0
  - pkgutil-resolve-name=1.3.10
  - ply=3.11
  - pooch=1.8.2
  - prometheus-cpp=1.3.0
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.51
  - propcache=0.3.1
  - protobuf=5.29.3
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=20.0.0
  - pyarrow-core=20.0.0
  - pybind11=2.13.6
  - pybind11-global=2.13.6
  - pyconify=0.2.1
  - pycparser=2.22
  - pydantic-compat=0.1.2
  - pydantic-extra-types=2.10.4
  - pydantic-settings=2.9.1
  - pygments=2.19.1
  - pyopengl=3.1.9
  - pyparsing=3.2.3
  - pyproject_hooks=1.2.0
  - pyqt=5.15.11
  - pyqt5-sip=12.17.0
  - pysocks=1.7.1
  - python=3.10.13
  - python-build=1.2.2.post1
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.0
  - python-elf=0.7.1
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - python-lmdb=1.6.2
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.10
  - pytorch=2.6.0
  - pytz=2025.2
  - pywavelets=1.8.0
  - pyyaml=6.0.2
  - pyzmq=26.4.0
  - qhull=2020.2
  - qt=5.15.15
  - qt-main=5.15.15
  - qt-webengine=5.15.15
  - qtconsole-base=5.6.1
  - qtpy=2.4.3
  - rav1e=0.7.1
  - re2=2024.07.02
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.3
  - resource_backed_dask_array=0.1.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=14.0.0
  - ruff=0.9.1
  - ruyaml=0.91.0
  - safetensors=0.5.3
  - scikit-learn=1.6.1
  - segment-anything=1.0
  - send2trash=1.8.2
  - setuptools=75.8.0
  - shellingham=1.5.4
  - sip=6.10.0
  - six=1.17.0
  - skan=0.12.1
  - sleef=3.8
  - snappy=1.2.1
  - sniffio=1.3.1
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sphinx=8.1.3
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sqlite=3.49.2
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - superqt=0.7.3
  - svt-av1=3.0.2
  - sympy=1.14.0
  - tabulate=0.9.0
  - tblib=3.1.0
  - tensorboard=2.19.0
  - tensorboard-data-server=0.7.0
  - terminado=0.17.1
  - threadpoolctl=3.5.0
  - tifffile=2022.4.8
  - timm=1.0.15
  - tinycss2=1.4.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.2.1
  - tomli-w=1.2.0
  - toolz=1.0.0
  - toposort=1.10
  - torch_em=0.7.9
  - torchvision=0.21.0
  - torchvision-extra-decoders=0.0.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typer=0.15.3
  - typer-slim=0.15.3
  - typer-slim-standard=0.15.3
  - typing-extensions=4.13.2
  - typing-inspection=0.4.0
  - typing_extensions=4.13.2
  - tzdata=2025a
  - unicodedata2=16.0.0
  - untokenize=0.1.1
  - urllib3=2.4.0
  - vigra=1.12.2
  - vispy=0.14.3
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.1.3
  - wheel=0.45.1
  - wrapt=1.17.2
  - x264=1!161.3030
  - x265=3.5
  - xarray=2024.11.0
  - xmlschema=4.1.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xsdata=24.3.1
  - xxhash=0.8.3
  - xyzservices=2022.9.0
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yarl=1.18.0
  - z5py=2.0.20
  - zarr=2.13.3
  - zeromq=4.3.5
  - zfp=1.0.1
  - zict=3.0.0
  - zipp=3.21.0
  - zlib=1.3.1
  - zlib-ng=2.2.4
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - app-model==0.3.1
      - asciitree==0.3.3
      - cellpose==3.1.1.1
      - certifi==2025.6.15
      - charset-normalizer==3.4.1
      - click==8.1.8
      - dask==2025.4.1
      - exceptiongroup==1.2.2
      - fastremap==1.15.2
      - fonttools==4.57.0
      - imagecodecs==2025.3.30
      - importlib-metadata==8.7.0
      - kiwisolver==1.4.8
      - llvmlite==0.44.0
      - matplotlib==3.10.1
      - narwhals==1.37.1
      - opencv-python-headless==4.11.0.86
      - partsegcore-compiled-backend==0.15.12
      - platformdirs==4.3.7
      - plotly==6.0.1
      - psygnal==0.12.0
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - roifile==2025.2.20
      - rpds-py==0.24.0
      - scikit-image==0.21.0
      - scipy==1.15.3
      - seaborn==0.13.2
      - sphinxcontrib-serializinghtml==2.0.0
      - torch==2.7.0
      - tornado==6.4.2
      - triangle==20250106
