name: autophagy_gui_env
channels:
  - conda-forge
dependencies:
  - python=3.9.19

  # Core scientific stack
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-image=0.22.0
  - scikit-learn=1.5.0
  - scipy=1.13.1       # Slightly older than 1.15.2 due to conda availability
  - matplotlib=3.8.4   # Slightly older than 3.10.1 but more stable
  - seaborn=0.13.2
  - tqdm=4.66.2
  - networkx=3.4.2
  - pillow=10.3.0
  - imageio=2.34.1
  - PyYAML=6.0.1
  - openpyxl=3.1.2

  # Napari + GUI
  - napari=0.4.19
  - napari-console=0.0.9
  - napari-svg=0.1.10
  - napari-plugin-engine=0.2.0
  - napari-plugin-manager=0.1.0
  - magicgui
  - qtpy
  - pyqt=5.15.9
  - superqt

  # Deep learning & segmentation
  - cellpose=2.2.3
  - torch=2.2.2
  - torchvision=0.17.2

  # Plotting
  - plotly=6.0.1

  # Typing and utilities
  - typing-extensions
  - pip=24.0

  # pip-only packages
  - pip:
      - pydantic==2.7.1
      - micro-sam==0.1.0
      - opencv-python-headless==4.11.0.86
